spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/dac
    driver-class-name: com.mysql.jdbc.Driver
    user: root
    password: 1qaz2wsx


oracle:
  jdbc:
    driver-class-name: oracle.jdbc.driver.OracleDriver
    url: jdbc:oracle:thin:@127.0.0.1:1521:orcl
    username: audit30dev1
    password: audit30dev1
sync:
  table:
    name: std_ugate
    #数据范围区分字段
    range-col: rec_time

jasypt:
  encryptor:
    bean: encryptorBean

sync-table:
  #
  tableNameList[0]: std_ugate
  tableNameList[1]: std_umap
  cron: 0 */1 * * * ?
  #数据范围区分字段
  rangeCol[0]: rec_time
  rangeCol[1]: rec_time
target:
  table:
    prefix:
      std: HNSTD_DEV_SESSION_
      ori: HNORI_DEV_SESSION_
# 日志
logging:
  level:
    org:
      springframework:
        security: DEBUG
  path: ../log
  file: ../log/ap.log
hive-table: hn_dev_session

sftp-upload:
  user: cloudera
  pwd: 56#byPac&*
  host: 134.176.83.84
  port: 22
  root: /app/cloudera/csv
  privateKey:
  passphrase:

solr-url: http://localhost:8983/solr/lhc_core

hive:
  jdbc: jdbc:hive2://192.168.0.121:10000/default
  type: com.alibaba.druid.pool.DruidDataSource
  driver-class-name: org.apache.hive.jdbc.HiveDriver
  user:
  password:
  max-active: 5
  initialSize: 3
  maxWait: 60000
  minIdle: 1
  timeBetweenEvictionRunsMillis: 60000
  minEvictableIdleTimeMillis: 300000
  testWhileIdle: true
  testOnBorrow: false
  testOnReturn: false
  poolPreparedStatements: true
  maxOpenPreparedStatements: 50
  removeAbandoned: true
  removeAbandonedTimeout: 180
