spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/dac
    driver-class-name: com.mysql.jdbc.Driver
    user: root
    password: 1qaz2wsx
  profiles:
    active: std-column-mapping,ori-column-mapping

oracle:
  jdbc:
    driver-class-name: oracle.jdbc.driver.OracleDriver
    url: jdbc:oracle:thin:@127.0.0.1:1521:orcl
    username: audit30dev1
    password: audit30dev1

jasypt:
  encryptor:
    bean: encryptorBean

sync-table:
  #同步表名
  tableNameList[0]: std_ugate
  tableNameList[1]: std_umap
  cron: 0 */5 * * * ?
  #数据范围区分字段
  rangeCol[0]: rec_time
  rangeCol[1]: rec_time
  range-type: day
  range-interval: -1
  start: 20200311000000
  end: 20200312000000
  switch: on
page-query:
  switch: on
  size: 10

target:
  table:
    prefix:
      std: HNSTD_DEV_SESSION_
      ori: HNORI_DEV_SESSION_
    rangeCol:
      std: operate_time
      ori: garther_time
    filter:
      std: device_type ='1'
      ori: device_type ='1'
# 日志
logging:
  file: ap.log

server:
  port: 8001

csv-path: /Users/alee/Downloads
csv-day-generate-switch: on
csv-data-filter: device_type ='1'
csv-file-ext:
sftp-switch: off



sftp-upload:
  user: cloudera
  pwd: 56#byPac&*
  host: 134.176.83.84
  port: 22
  root: /app/cloudera/csv
  privateKey:
  passphrase:


hive:
  jdbc: jdbc:hive2://134.176.83.83:10000/default
  type: com.alibaba.druid.pool.DruidDataSource
  driver-class-name: org.apache.hive.jdbc.HiveDriver
  user:
  password:
  max-active: 5
  initialSize: 3
  maxWait: 60000
  minIdle: 1
  timeBetweenEvictionRunsMillis: 60000
  minEvictableIdleTimeMillis: 300000
  testWhileIdle: true
  testOnBorrow: false
  testOnReturn: false
  poolPreparedStatements: true
  maxOpenPreparedStatements: 50
  removeAbandoned: true
  removeAbandonedTimeout: 180

#标准日志表字段映射配置
column-mapping-std:
  columnMappingMap:
    SESSION_ID: SESSION_ID
    MAIN_ACCOUNT_NAME: PRACCT_NAME
    REAL_NAME: REAL_NAME
    DEP_NAME: ORG_NAME
    SUB_ACCOUNT_NAME: SLAVE_ACCOUNT_NAME
    CLIENT_IP: client_ip
    CLIENT_PORT: CLIENT_PORT
    CLIENT_SOURCE_NMAE: CLIENT_MACHINE_NAME
    CLIENT_HOST_MANAGER: CLIENT_HOST_MANAGER
    CLIENT_BES_SYS_NAME: CLIENT_BES_SYS_NAME
    CLIENT_BES_SYS_MANAGER: CLIENT_BES_SYS_MANAGER
    CLIENT_USER: CLIENT_USER
    CLIENT_PRG: CLIENT_PRG
    OPERATE_TIME: OPT_TIME
    OPERATE_CONTENT: DESCRIPTION_CMD
    OPERATE_CMD: DESCRIPTION_CMD
    DES_IP: DST_IP
    DES_PORT: DSP_PORT
    DES_SOURCE_NAME: DST_NAME
    DES_HOST_MANAGER: DES_HOST_MANAGER
    DES_SYS_NAME: DES_SYS_NAME
    DES_SYS_MANAGER: DES_SYS_MANAGER
    DEVICE_TYPE: DEVICE_TYPE
    ACCESS_ID: ACCESS_ID
    SQL_ID: SQL_ID
    PO_ID: PO_ID
    SHG_ID: SHG_ID
    OP_TYPE: OP_TYPE
    COST: COST
    POLICY_ID: POLICY_ID
    R_LEVEL: R_LEVEL
    BACK_RESULT: BACK_RESULT
    DATA_SET: DATA_SET
    EFFECT_ROW: EFFECT_ROW
    RESULT_CODE: RESULT_CODE
    RESULT_FLAG: RESULT_FLAG
    SRC_MAC: SRC_MAC
    DES_MAC: DES_MAC
    APP_TYPE_ID: APP_TYPE_ID
    OPERATE_TABLE_NAME: OPERATE_TABLE_NAME
    DB_NAME: DB_NAME
    SID: SID
    RELATE_NAME: RELATE_NAME
    RELATE_SIP: RELATE_SIP
    OBJ_DETAIL: OBJ_DETAIL
    LOGIN_TIME: LOGIN_TIME
    LOGOUT_TIME: LOGOUT_TIME
    SCAN_TIME: SCAN_TIME
    TYPE: TYPE
    STD_TIME: REC_TIME
    C1: C1
    C2: C2
    C3: C3
    C4: C4
    C5: C5
    C6: C6
    C7: C7
  defaultValueMap:
    DEVICE_TYPE: 1
#原始日志表字段映射
column-mapping-ori:
  columnMappingMap:
    SESSION_ID: SESSION_ID
    MAIN_ACCOUNT_NAME: PRACCT_NAME
    REAL_NAME: REAL_NAME
    DEP_NAME: ORG_NAME
    SUB_ACCOUNT_NAME: SLAVE_ACCOUNT_NAME
    CLIENT_IP: client_ip
    CLIENT_PORT: CLIENT_PORT
    CLIENT_SOURCE_NMAE: CLIENT_MACHINE_NAME
    CLIENT_HOST_MANAGER: CLIENT_HOST_MANAGER
    CLIENT_BES_SYS_NAME: CLIENT_BES_SYS_NAME
    CLIENT_BES_SYS_MANAGER: CLIENT_BES_SYS_MANAGER
    CLIENT_USER: CLIENT_USER
    CLIENT_PRG: CLIENT_PRG
    OPERATE_TIME: OPT_TIME
    OPERATE_CONTENT: DESCRIPTION_CMD
    OPERATE_CMD: DESCRIPTION_CMD
    DES_IP: DST_IP
    DES_PORT: DSP_PORT
    DES_SOURCE_NAME: DST_NAME
    DES_HOST_MANAGER: DES_HOST_MANAGER
    DES_SYS_NAME: DES_SYS_NAME
    DES_SYS_MANAGER: DES_SYS_MANAGER
    DEVICE_TYPE: DEVICE_TYPE:1
    ACCESS_ID: ACCESS_ID
    SQL_ID: SQL_ID
    PO_ID: PO_ID
    SHG_ID: SHG_ID
    OP_TYPE: OP_TYPE
    COST: COST
    POLICY_ID: POLICY_ID
    R_LEVEL: R_LEVEL
    BACK_RESULT: BACK_RESULT
    DATA_SET: DATA_SET
    EFFECT_ROW: EFFECT_ROW
    RESULT_CODE: RESULT_CODE
    RESULT_FLAG: RESULT_FLAG
    SRC_MAC: CLIENT_MAC
    DES_MAC: DES_MAC
    APP_TYPE_ID: APP_TYPE_ID
    OPERATE_TABLE_NAME: OPERATE_TABLE_NAME
    DB_NAME: DB_NAME
    SID: SID
    RELATE_NAME: RELATE_NAME
    RELATE_SIP: RELATE_SIP
    OBJ_DETAIL: OBJ_DETAIL
    LOGIN_TIME: LOGIN_TIME
    LOGOUT_TIME: LOGOUT_TIME
    SCAN_TIME: SCAN_TIME
    TYPE: TYPE
    GARTHER_TIME: REC_TIME
    C1: C1
    C2: C2
    C3: C3
    C4: C4
    C5: C5
    C6: C6
    C7: C7
specialColumn: DEVICE_TYPE,TYPE,OBJ_DETAIL