column-mapping-std:
  columnMappingMap:
    SESSION_ID: SESSION_ID
    MAIN_ACCOUNT_NAME: PRACCT_NAME
    REAL_NAME: REAL_NAME
    DEP_NAME: ORG_NAME
    SUB_ACCOUNT_NAME: SLAVE_ACCOUNT_NAME
    CLIENT_IP: client_ip
    CLIENT_PORT: CLIENT_PORT
    CLIENT_SOURCE_NMAE: CLIENT_MACHINE_NAME
    CLIENT_HOST_MANAGER: CLIENT_HOST_MANAGER
    CLIENT_BES_SYS_NAME: CLIENT_BES_SYS_NAME
    CLIENT_BES_SYS_MANAGER: CLIENT_BES_SYS_MANAGER
    CLIENT_USER: CLIENT_USER
    CLIENT_PRG: CLIENT_PRG
    OPERATE_TIME: OPT_TIME
    OPERATE_CONTENT: DESCRIPTION_CMD
    OPERATE_CMD: DESCRIPTION_CMD
    DES_IP: DST_IP
    DES_PORT: DSP_PORT
    DES_SOURCE_NAME: DST_NAME
    DES_HOST_MANAGER: DES_HOST_MANAGER
    DES_SYS_NAME: DES_SYS_NAME
    DES_SYS_MANAGER: DES_SYS_MANAGER
    DEVICE_TYPE: DEVICE_TYPE
    ACCESS_ID: ACCESS_ID
    SQL_ID: SQL_ID
    PO_ID: PO_ID
    SHG_ID: SHG_ID
    OP_TYPE: OP_TYPE
    COST: COST
    POLICY_ID: POLICY_ID
    R_LEVEL: R_LEVEL
    BACK_RESULT: BACK_RESULT
    DATA_SET: DATA_SET
    EFFECT_ROW: EFFECT_ROW
    RESULT_CODE: RESULT_CODE
    RESULT_FLAG: RESULT_FLAG
    SRC_MAC: SRC_MAC
    DES_MAC: DES_MAC
    APP_TYPE_ID: APP_TYPE_ID
    OPERATE_TABLE_NAME: OPERATE_TABLE_NAME
    DB_NAME: DB_NAME
    SID: SID
    RELATE_NAME: RELATE_NAME
    RELATE_SIP: RELATE_SIP
    OBJ_DETAIL: OBJ_DETAIL
    LOGIN_TIME: LOGIN_TIME
    LOGOUT_TIME: LOGOUT_TIME
    SCAN_TIME: SCAN_TIME
    TYPE: TYPE
    STD_TIME: REC_TIME
    C1: C1
    C2: C2
    C3: C3
    C4: C4
    C5: C5
    C6: C6
    C7: C7

